### PR TITLE
Download Seattle library

### PR DESCRIPTION
**Pull request by raffaem**
Download Seattle library if it wasn't downloaded already

### CODE REVIEW

**Comment by mine-cetinkaya-rundel** [comment]
@hadley Would you take a look at this one? I agree with the suggestion and it works, however I'm unable to re-render the chapter due to a different error:

```r
seattle_csv |>
  group_by(CheckoutYear) |>
  write_dataset(path = pq_path, format = "parquet")
```

gives 

```
Error:
! Invalid: In CSV column #7: Row #83240: CSV conversion error to null: invalid value '9781504752848'
```

We do need to re-render this chapter and update the freeze since the WIP status is still visible on the book website.

**Comment by mine-cetinkaya-rundel** [comment]
Related to #1374

**Comment by hadley** [comment]
Yeah, this seems fine to me.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!

**Pull request merged**
