### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by jennybc**

### CODE REVIEW

**Comment by hadley** [comment]
Thanks!

**Comment by wma1125** [comment]
Hi Jenny,

i'm using googlehsheets in R. .there is some issues when I tried to use .rds for authentication without interaction with brower. it seems failed refreshing and I have to use gs_auth() to re-enter my authentication in browser.

gs_auth(token = "ttt.rds", verbose = FALSE)

Auto-refreshing stale OAuth token.
Error in function_list[[k]](value) : Unauthorized (HTTP 401).
In addition: Warning message:
Unable to refresh token

**Comment by jennybc** [comment]
@wma1125 Can you open an issue on googlesheets? Currently this conversation is happening in a thread on the r4ds book.

**Comment by wma1125** [comment]
issue opened 
https://github.com/hadley/r4ds/issues/135

**Pull request merged**
