### PR TITLE
Update intro.Rmd

### PR DESCRIPTION
**Pull request by sibusiso16**
"I" not sure if its you or Garrett and most of the time, you use "we".

### CODE REVIEW

**Comment by hadley** [comment]
Garrett and I reserve "we" to mean the author + the reader. (This would be easier if English, like some languages, distinguished between we-including-you and we-excluding-you)

**Comment by sibusiso16** [comment]
Good point. I was coming from the view point of "we - Hadley and Garrett" and "you - the reader".

**Comment by sibusiso16** [comment]
Hi Hadley. I wanted to ask if it's possible for you to show/include a way of updating Rstudio and base R without downloading the file again on the section where you indicate where to download the tools from.

**Comment by hadley** [comment]
Currently, you need to go to the website and download them

**Pull request closed without merging**
