### PR TITLE
Update intro.Rmd

### PR DESCRIPTION
**Pull request by sibusiso16**
Typo. 

I'm not if I once seen a reference to Jenny's reprex example here but I was expecting to see a link to her github page that shows how to do the reprex.

Under the Acknowledgements section, were you thank everyone who contributed via GitHub, you seem to be pulling the username and full name (Jennifer (Jenny) Bryan, @jennybc) for the contributors.

### CODE REVIEW

**Comment by hadley** [comment]
reprex isn't on CRAN yet, and I didn't want to get into the details of installing from github.

**Comment by sibusiso16** [comment]
Sorry, the page kept jumping to the top when i was trying to put the "f" in diference. Sorry about this..

**Comment by sibusiso16** [comment]
I have removed the 'f'. ;)

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
