### PR TITLE
fix typo: s

### PR DESCRIPTION
**Pull request by schuess**

### CODE REVIEW

**Comment by hadley** [comment]
Could you please batch these up into a few bigger PRs?

**Comment by schuess** [comment]
Sure -- I don't know how to do that, but I'll ask a colleague on Tuesday.

**Comment by schuess** [comment]
I batched all the others into a single request. I left the graph one separate since my guess about what you were aiming for might be wrong.

Thanks for making this available!

**Comment by hadley** [comment]
Great, thanks!

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
