### PR TITLE
explore.Rmd Introduction

### PR DESCRIPTION
**Pull request by lindbrook**

### CODE REVIEW

**Comment by garrettgman** [comment]
@lindbrook thank you for your enthusiasm here. I'm reluctant to closely review your editorial rewrite of the book since our O'Reilly editor will also give it a rewrite. Can you provide more information about your choices here? e.g. do you have some experience as an editor? Can you describe the style guide that you are rewriting the text to conform to? I'm looking for an efficient way to decide whether to adopt the changes wholecloth or not. Thanks.

**Comment by hadley** [comment]
@garrettgman Peter did this for Advanced R and R Packages

**Comment by lindbrook** [comment]
No worries. There's no benefit to duplicating the work of an editor,
especially if there's a style guide etc. Feel free to close the pull
request.

**Comment by garrettgman** [comment]
Those books both turned out great. @linbrook, now I'm especially interested in your style guide, but mostly to learn from it :)

**Comment by hadley** [comment]
Unfortunately it's been heavily rewritten since these changes :/

**Pull request closed without merging**
